NUMBER_OF_HORIZONTAL_BLOCKS = 50
NUMBER_OF_VERTICAL_BLOCKS = 30
NUMBER_OF_OBSTACLES = 50
OBSTACLES_LENGTH_MAXIMUM = 10

BLOCK_SIZE = 20
WIDTH = NUMBER_OF_HORIZONTAL_BLOCKS*BLOCK_SIZE
HEIGHT = NUMBER_OF_VERTICAL_BLOCKS*BLOCK_SIZE

BLACK = [0, 0, 0]
WHITE = [250, 250, 250]

FPS = 30
