NUMBER_OF_HORIZONTAL_BLOCKS = 120
NUMBER_OF_VERTICAL_BLOCKS = 80
NUMBER_OF_OBSTACLES = 75
OBSTACLES_LENGTH_MAXIMUM = 150

BLOCK_SIZE = 10
HERO_SiZE_X = 20
HERO_SIZE_Y = 20
WIDTH = NUMBER_OF_HORIZONTAL_BLOCKS*BLOCK_SIZE
HEIGHT = NUMBER_OF_VERTICAL_BLOCKS*BLOCK_SIZE

HERO_X = 2*HERO_SiZE_X
HERO_Y = 2*HERO_SIZE_Y

BLACK = [0, 0, 0]
WHITE = [250, 250, 250]
GREEN = [0, 250, 0]


MOVE_SPEED = 5
JUMP_POWER = 6
GRAVITY = 0.15  # Сила, которая будет тянуть нас вниз



FPS = 60
